/**
 * BHR-G schema — GENERATED from the official XSD by scripts/codegen-schema.ts.
 * Do not edit by hand. Structural warts are supplied by ./bhrg-curation.ts.
 *
 * @generated from https://schema.broservices.nl/xsd/dsbhrg/3.1/dsbhr-g-messages.xsd
 */
/* eslint-disable @typescript-eslint/naming-convention -- field keys are XSD element names (e.g. `fraction0to0.2um`) */

import { array, boolean, code, date, number, object, text } from "../core/producer.js";
import { gmlLocation } from "./common-fields.js";


export const BHRG_PRODUCER = object({
  fields: {
    broId: text("./brocom:broId"),
    deliveryAccountableParty: text("./brocom:deliveryAccountableParty"),
    objectIdAccountableParty: text("./brocom:objectIdAccountableParty"),
    deliveryResponsibleParty: text("./brocom:deliveryResponsibleParty"),
    qualityRegime: text("./brocom:qualityRegime"),
    deliveryContext: code("./dsbhrg:deliveryContext"),
    surveyPurpose: code("./dsbhrg:surveyPurpose"),
    discipline: code("./dsbhrg:discipline"),
    surveyProcedure: code("./dsbhrg:surveyProcedure"),
    researchReportDate: date("./dsbhrg:researchReportDate"),
    researchOperator: object({ at: "./dsbhrg:researchOperator", fields: {
      chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
      europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
    } }),
    siteCharacteristicDetermined: boolean("./dsbhrg:siteCharacteristicDetermined"),
    registrationHistory: object({ at: "./dsbhrg:registrationHistory", fields: {
      objectRegistrationTime: date("./brocom:objectRegistrationTime"),
      registrationStatus: code("./brocom:registrationStatus"),
      latestAdditionTime: date("./brocom:latestAdditionTime"),
      registrationCompletionTime: date("./brocom:registrationCompletionTime"),
      corrected: boolean("./brocom:corrected"),
      latestCorrectionTime: date("./brocom:latestCorrectionTime"),
      underReview: boolean("./brocom:underReview"),
      underReviewTime: date("./brocom:underReviewTime"),
      deregistered: boolean("./brocom:deregistered"),
      deregistrationTime: date("./brocom:deregistrationTime"),
      reregistered: boolean("./brocom:reregistered"),
      reregistrationTime: date("./brocom:reregistrationTime"),
    } }),
    nITGCode: text("./dsbhrg:NITGCode"),
    reportHistory: object({ at: "./dsbhrg:reportHistory", fields: {
      event: array({ each: "./bhrgcom:event", item: object({ fields: {
        date: date("./bhrgcom:date"),
        name: code("./bhrgcom:name"),
      } }) }),
    } }),
    deliveredLocation: object({ at: "./dsbhrg:deliveredLocation", fields: {
      location: gmlLocation("./bhrgcom:location"),
      horizontalPositioningDate: date("./bhrgcom:horizontalPositioningDate"),
      horizontalPositioningMethod: code("./bhrgcom:horizontalPositioningMethod"),
      horizontalPositioningOperator: object({ at: "./bhrgcom:horizontalPositioningOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
    } }),
    deliveredVerticalPosition: object({ at: "./dsbhrg:deliveredVerticalPosition", fields: {
      localVerticalReferencePoint: code("./bhrgcom:localVerticalReferencePoint"),
      offset: number("./bhrgcom:offset"),
      waterDepth: number("./bhrgcom:waterDepth"),
      verticalDatum: code("./bhrgcom:verticalDatum"),
      verticalPositioningDate: date("./bhrgcom:verticalPositioningDate"),
      verticalPositioningMethod: code("./bhrgcom:verticalPositioningMethod"),
      verticalPositioningOperator: object({ at: "./bhrgcom:verticalPositioningOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
    } }),
    standardizedLocation: object({ at: "./dsbhrg:standardizedLocation", fields: {
      location: gmlLocation("./brocom:location"),
      coordinateTransformation: code("./brocom:coordinateTransformation"),
    } }),
    siteCharacteristic: object({ at: "./dsbhrg:siteCharacteristic", fields: {
      soilUse: code("./bhrgcom:soilUse"),
      positionOnGroundBody: code("./bhrgcom:positionOnGroundBody"),
      landscapeElement: code("./bhrgcom:landscapeElement"),
      hydrologicalSetting: code("./bhrgcom:hydrologicalSetting"),
      currentProcess: code("./bhrgcom:currentProcess"),
      temporaryChange: code("./bhrgcom:temporaryChange"),
    } }),
    boring: object({ at: "./dsbhrg:boring/bhrgcom:Boring", fields: {
      boringStartDate: date("./bhrgcom:boringStartDate"),
      boringEndDate: date("./bhrgcom:boringEndDate"),
      preparation: code("./bhrgcom:preparation"),
      finalDepthPreparation: number("./bhrgcom:finalDepthPreparation"),
      trajectoryExcavated: boolean("./bhrgcom:trajectoryExcavated"),
      finalDepthExcavation: number("./bhrgcom:finalDepthExcavation"),
      rockReached: boolean("./bhrgcom:rockReached"),
      boringProcedure: array({ each: "./bhrgcom:boringProcedure", item: code() }),
      finalDepthBoring: number("./bhrgcom:finalDepthBoring"),
      stopCriterion: code("./bhrgcom:stopCriterion"),
      temporaryCasingUsed: boolean("./bhrgcom:temporaryCasingUsed"),
      finalDepthTemporaryCasing: number("./bhrgcom:finalDepthTemporaryCasing"),
      flushingAdditiveUsed: text("./bhrgcom:flushingAdditiveUsed"),
      flushingAdditive: code("./bhrgcom:flushingAdditive"),
      groundwaterLevel: number("./bhrgcom:groundwaterLevel"),
      samplingProcedure: code("./bhrgcom:samplingProcedure"),
      finalDepthSampling: number("./bhrgcom:finalDepthSampling"),
      subsurfaceContaminated: text("./bhrgcom:subsurfaceContaminated"),
      boreholeCompleted: text("./bhrgcom:boreholeCompleted"),
      boringOperator: object({ at: "./bhrgcom:boringOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
      excavatedLayer: array({ each: "./bhrgcom:excavatedLayer/bhrgcom:ExcavatedLayer", item: object({ fields: {
        upperBoundary: number("./bhrgcom:upperBoundary"),
        lowerBoundary: number("./bhrgcom:lowerBoundary"),
        excavatedMaterial: code("./bhrgcom:excavatedMaterial"),
      } }) }),
      boredInterval: array({ each: "./bhrgcom:boredInterval/bhrgcom:BoredInterval", item: object({ fields: {
        beginDepth: number("./bhrgcom:beginDepth"),
        endDepth: number("./bhrgcom:endDepth"),
        boringTechnique: code("./bhrgcom:boringTechnique"),
        boredDiameter: number("./bhrgcom:boredDiameter"),
      } }) }),
      sampledInterval: array({ each: "./bhrgcom:sampledInterval/bhrgcom:SampledInterval", item: object({ fields: {
        beginDepth: number("./bhrgcom:beginDepth"),
        endDepth: number("./bhrgcom:endDepth"),
        preTreatment: code("./bhrgcom:preTreatment"),
        samplingMethod: code("./bhrgcom:samplingMethod"),
        samplingQuality: code("./bhrgcom:samplingQuality"),
        orientatedSampled: boolean("./bhrgcom:orientatedSampled"),
        sampler: object({ at: "./bhrgcom:sampler", fields: {
          samplerType: code("./bhrgcom:samplerType"),
          sampleContainerDiameter: number("./bhrgcom:sampleContainerDiameter"),
          sampleContainerLength: number("./bhrgcom:sampleContainerLength"),
          cuttingShoeInsideDiameter: number("./bhrgcom:cuttingShoeInsideDiameter"),
          stockingUsed: boolean("./bhrgcom:stockingUsed"),
          rightAngledCuttingShoe: boolean("./bhrgcom:rightAngledCuttingShoe"),
          taperAngle: number("./bhrgcom:taperAngle"),
          cuttingShoeOutsideDiameter: number("./bhrgcom:cuttingShoeOutsideDiameter"),
          lubricationFluidUsed: boolean("./bhrgcom:lubricationFluidUsed"),
          coreCatcherPresent: boolean("./bhrgcom:coreCatcherPresent"),
          pistonPresent: boolean("./bhrgcom:pistonPresent"),
        } }),
      } }) }),
      contaminatedInterval: array({ each: "./bhrgcom:contaminatedInterval/bhrgcom:ContaminatedInterval", item: object({ fields: {
        beginDepth: number("./bhrgcom:beginDepth"),
        endDepth: number("./bhrgcom:endDepth"),
      } }) }),
      completedInterval: array({ each: "./bhrgcom:completedInterval/bhrgcom:CompletedInterval", item: object({ fields: {
        beginDepth: number("./bhrgcom:beginDepth"),
        endDepth: number("./bhrgcom:endDepth"),
        permanentCasingPresent: text("./bhrgcom:permanentCasingPresent"),
        diameterPermanentCasing: number("./bhrgcom:diameterPermanentCasing"),
        materialPermanentCasing: code("./bhrgcom:materialPermanentCasing"),
        backfillMaterial: code("./bhrgcom:backfillMaterial"),
        backfillMaterialWashed: boolean("./bhrgcom:backfillMaterialWashed"),
        backfillMaterialCertified: boolean("./bhrgcom:backfillMaterialCertified"),
      } }) }),
    } }),
    fluidMudLayer: object({ at: "./dsbhrg:fluidMudLayer/bhrgcom:FluidMudLayer", fields: {
      thickness: number("./bhrgcom:thickness"),
      colour: code("./bhrgcom:colour"),
      upperBoundaryPositioningMethod: code("./bhrgcom:upperBoundaryPositioningMethod"),
      lowerBoundaryPositioningMethod: code("./bhrgcom:lowerBoundaryPositioningMethod"),
    } }),
    boreholeSampleDescription: object({ at: "./dsbhrg:boreholeSampleDescription/bhrgcom:BoreholeSampleDescription", fields: {
      descriptionReportDate: date("./bhrgcom:descriptionReportDate"),
      descriptionProcedure: code("./bhrgcom:descriptionProcedure"),
      utensil: code("./bhrgcom:utensil"),
      descriptionOperator: object({ at: "./bhrgcom:descriptionOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
      descriptiveBoreholeLog: array({ each: "./bhrgcom:descriptiveBoreholeLog/bhrgcom:DescriptiveBoreholeLog", item: object({ fields: {
        descriptionQuality: code("./bhrgcom:descriptionQuality"),
        describedSamplesQuality: code("./bhrgcom:describedSamplesQuality"),
        continuouslySampled: text("./bhrgcom:continuouslySampled"),
        descriptionLocation: code("./bhrgcom:descriptionLocation"),
        describedMaterial: code("./bhrgcom:describedMaterial"),
        sampleMoistness: code("./bhrgcom:sampleMoistness"),
        meanHighestGroundwaterLevel: number("./bhrgcom:meanHighestGroundwaterLevel"),
        meanLowestGroundwaterLevel: number("./bhrgcom:meanLowestGroundwaterLevel"),
        layer: array({ each: "./bhrgcom:layer/bhrgcom:Layer", item: object({ fields: {
          upperBoundary: number("./bhrgcom:upperBoundary"),
          upperBoundaryDetermination: code("./bhrgcom:upperBoundaryDetermination"),
          lowerBoundary: number("./bhrgcom:lowerBoundary"),
          lowerBoundaryDetermination: code("./bhrgcom:lowerBoundaryDetermination"),
          anthropogenic: text("./bhrgcom:anthropogenic"),
          activityType: code("./bhrgcom:activityType"),
          specialMaterial: code("./bhrgcom:specialMaterial"),
          postSedimentary: text("./bhrgcom:postSedimentary"),
          horizonCode: code("./bhrgcom:horizonCode"),
          rooted: text("./bhrgcom:rooted"),
          humanTrace: code("./bhrgcom:humanTrace"),
          geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
          internalStructureIntact: boolean("./bhrgcom:internalStructureIntact"),
          bioturbated: boolean("./bhrgcom:bioturbated"),
          slant: boolean("./bhrgcom:slant"),
          structure: array({ each: "./bhrgcom:structure", item: code() }),
          verticalTrend: array({ each: "./bhrgcom:verticalTrend", item: code() }),
          archeologicalConstituent: array({ each: "./bhrgcom:archeologicalConstituent", item: object({ fields: {
            constituentType: code("./bhrgcom:constituentType"),
            percentageClass: code("./bhrgcom:percentageClass"),
            archiveClass: code("./bhrgcom:archiveClass"),
          } }) }),
          layerComponent: array({ each: "./bhrgcom:layerComponent", item: object({ fields: {
            layerProportion: number("./bhrgcom:layerProportion"),
            soil: object({ at: "./bhrgcom:soil", fields: {
              geologicalSoilName: code("./bhrgcom:geologicalSoilName"),
              geotechnicalSoilName: code("./bhrgcom:geotechnicalSoilName"),
              soilNameNEN5104: code("./bhrgcom:soilNameNEN5104"),
              gravelContentClass: code("./bhrgcom:gravelContentClass"),
              micaContentClass: code("./bhrgcom:micaContentClass"),
              micaContentClassArchive: code("./bhrgcom:micaContentClassArchive"),
              organicMatterContentClass: code("./bhrgcom:organicMatterContentClass"),
              organicMatterContentClassNEN5104: code("./bhrgcom:organicMatterContentClassNEN5104"),
              shellMatterContentClass: code("./bhrgcom:shellMatterContentClass"),
              shellMatterContentClassArchive: code("./bhrgcom:shellMatterContentClassArchive"),
              veryCoarseFractionContentClass: array({ each: "./bhrgcom:veryCoarseFractionContentClass", item: code() }),
              veryCoarseFractionContentClassArchive: array({ each: "./bhrgcom:veryCoarseFractionContentClassArchive", item: code() }),
              glauconiteContentClass: code("./bhrgcom:glauconiteContentClass"),
              glauconiteContentClassArchive: code("./bhrgcom:glauconiteContentClassArchive"),
              carbonateContentClass: code("./bhrgcom:carbonateContentClass"),
              colour: code("./bhrgcom:colour"),
              mottled: boolean("./bhrgcom:mottled"),
              fineSoilConsistency: code("./bhrgcom:fineSoilConsistency"),
              organicSoilConsistency: code("./bhrgcom:organicSoilConsistency"),
              sedimentaryPhenomenon: code("./bhrgcom:sedimentaryPhenomenon"),
              organicSoilTexture: code("./bhrgcom:organicSoilTexture"),
              particularConstituent: array({ each: "./bhrgcom:particularConstituent", item: object({ fields: {
                constituentType: code("./bhrgcom:constituentType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
              anomalousLayer: array({ each: "./bhrgcom:anomalousLayer", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                rockType: code("./bhrgcom:rockType"),
                layerProportion: number("./bhrgcom:layerProportion"),
                layerProportionClass: code("./bhrgcom:layerProportionClass"),
                layerProportionClassArchive: code("./bhrgcom:layerProportionClassArchive"),
                stratumThicknessClass: code("./bhrgcom:stratumThicknessClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
                cemented: boolean("./bhrgcom:cemented"),
              } }) }),
              chunk: array({ each: "./bhrgcom:chunk", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                sizeClass: code("./bhrgcom:sizeClass"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
                cemented: boolean("./bhrgcom:cemented"),
              } }) }),
              gravelFraction: object({ at: "./bhrgcom:gravelFraction", fields: {
                gravelMedianClass: code("./bhrgcom:gravelMedianClass"),
                angularity: code("./bhrgcom:angularity"),
                fineGravelContentClass: code("./bhrgcom:fineGravelContentClass"),
                mediumCoarseGravelContentClass: code("./bhrgcom:mediumCoarseGravelContentClass"),
                veryCoarseGravelContentClass: code("./bhrgcom:veryCoarseGravelContentClass"),
                ventifactPresent: text("./bhrgcom:ventifactPresent"),
                sphericity: code("./bhrgcom:sphericity"),
                variegation: code("./bhrgcom:variegation"),
                estimatedMedian: number("./bhrgcom:estimatedMedian"),
                gravelProvenance: code("./bhrgcom:gravelProvenance"),
                gravelConstituent: array({ each: "./bhrgcom:gravelConstituent", item: object({ fields: {
                  gravelType: code("./bhrgcom:gravelType"),
                  fractionProportion: code("./bhrgcom:fractionProportion"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              sandFraction: object({ at: "./bhrgcom:sandFraction", fields: {
                darkGrainContentClass: code("./bhrgcom:darkGrainContentClass"),
                darkGrainContentClassArchive: code("./bhrgcom:darkGrainContentClassArchive"),
                angularity: code("./bhrgcom:angularity"),
                sandMedianClass: code("./bhrgcom:sandMedianClass"),
                sandSorting: code("./bhrgcom:sandSorting"),
                variegation: code("./bhrgcom:variegation"),
                anomalouslyCoarseContentClass: code("./bhrgcom:anomalouslyCoarseContentClass"),
                anomalouslyCoarseContentClassArchive: code("./bhrgcom:anomalouslyCoarseContentClassArchive"),
                granuleContentClass: code("./bhrgcom:granuleContentClass"),
                granuleContentClassArchive: code("./bhrgcom:granuleContentClassArchive"),
                estimatedMedian: number("./bhrgcom:estimatedMedian"),
                sandConstituent: array({ each: "./bhrgcom:sandConstituent", item: object({ fields: {
                  grainColour: code("./bhrgcom:grainColour"),
                  percentageClass: code("./bhrgcom:percentageClass"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              shellFraction: object({ at: "./bhrgcom:shellFraction", fields: {
                gritContentClass: code("./bhrgcom:gritContentClass"),
                fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
                remainsContentClass: code("./bhrgcom:remainsContentClass"),
                wholeContentClass: code("./bhrgcom:wholeContentClass"),
                doublets: boolean("./bhrgcom:doublets"),
                thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
                thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
                inSitu: boolean("./bhrgcom:inSitu"),
                weatheringDegree: code("./bhrgcom:weatheringDegree"),
                shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                  shellTaxon: code("./bhrgcom:shellTaxon"),
                  relativeAbundance: number("./bhrgcom:relativeAbundance"),
                  relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                  relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
                } }) }),
              } }),
              shellFractionArchive: object({ at: "./bhrgcom:shellFractionArchive", fields: {
                gritContentClass: code("./bhrgcom:gritContentClass"),
                fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
                remainsContentClass: code("./bhrgcom:remainsContentClass"),
                wholeContentClass: code("./bhrgcom:wholeContentClass"),
                doublets: boolean("./bhrgcom:doublets"),
                thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
                thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
                weatheringDegree: code("./bhrgcom:weatheringDegree"),
                shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                  shellTaxon: code("./bhrgcom:shellTaxon"),
                  relativeAbundance: number("./bhrgcom:relativeAbundance"),
                  relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                  relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
                } }) }),
              } }),
              peatFraction: object({ at: "./bhrgcom:peatFraction", fields: {
                peatType: code("./bhrgcom:peatType"),
                peatConstituent: array({ each: "./bhrgcom:peatConstituent", item: object({ fields: {
                  plantRemainType: code("./bhrgcom:plantRemainType"),
                  percentageClass: code("./bhrgcom:percentageClass"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              munsellColour: object({ at: "./bhrgcom:munsellColour", fields: {
                munsellHue: code("./bhrgcom:munsellHue"),
                munsellValue: code("./bhrgcom:munsellValue"),
                munsellChroma: code("./bhrgcom:munsellChroma"),
              } }),
              mottle: array({ each: "./bhrgcom:mottle", item: object({ fields: {
                colour: code("./bhrgcom:colour"),
                density: code("./bhrgcom:density"),
                inBands: text("./bhrgcom:inBands"),
              } }) }),
              inclusion: array({ each: "./bhrgcom:inclusion", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              } }) }),
              sedimentLens: array({ each: "./bhrgcom:sedimentLens", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              } }) }),
              animalFossil: array({ each: "./bhrgcom:animalFossil", item: object({ fields: {
                animalFossilType: code("./bhrgcom:animalFossilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
              fractionDistribution: object({ at: "./bhrgcom:fractionDistribution", fields: {
                fractionDistributionComplete: boolean("./bhrgcom:fractionDistributionComplete"),
                estimatedMassProportionOrganicMatter: number("./bhrgcom:estimatedMassProportionOrganicMatter"),
                estimatedMassProportionShellMatter: number("./bhrgcom:estimatedMassProportionShellMatter"),
                estimatedVolumeProportionShellMatter: number("./bhrgcom:estimatedVolumeProportionShellMatter"),
                estimatedMassProportionShell: number("./bhrgcom:estimatedMassProportionShell"),
                estimatedMassProportionGravel: number("./bhrgcom:estimatedMassProportionGravel"),
                estimatedVolumeProportionGravel: number("./bhrgcom:estimatedVolumeProportionGravel"),
                fineFractionDistributionGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionGravellyMineralSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionShellySoil: object({ at: "./bhrgcom:fineFractionDistributionShellySoil", fields: {
                  estimatedVolumeProportionSand: number("./bhrgcom:estimatedVolumeProportionSand"),
                  estimatedVolumeProportionSilt: number("./bhrgcom:estimatedVolumeProportionSilt"),
                  estimatedVolumeProportionLutum: number("./bhrgcom:estimatedVolumeProportionLutum"),
                } }),
                fineFractionDistributionShellySoilArchive: object({ at: "./bhrgcom:fineFractionDistributionShellySoilArchive", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionOrganicSoil: object({ at: "./bhrgcom:fineFractionDistributionOrganicSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionNonGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionNonGravellyMineralSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
              } }),
            } }),
          } }) }),
          thinStratum: array({ each: "./bhrgcom:thinStratum", item: object({ fields: {
            layerProportion: number("./bhrgcom:layerProportion"),
            layerProportionClass: code("./bhrgcom:layerProportionClass"),
            layerProportionClassArchive: code("./bhrgcom:layerProportionClassArchive"),
            stratumThicknessClass: code("./bhrgcom:stratumThicknessClass"),
            geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
            soil: object({ at: "./bhrgcom:soil", fields: {
              geologicalSoilName: code("./bhrgcom:geologicalSoilName"),
              geotechnicalSoilName: code("./bhrgcom:geotechnicalSoilName"),
              soilNameNEN5104: code("./bhrgcom:soilNameNEN5104"),
              gravelContentClass: code("./bhrgcom:gravelContentClass"),
              micaContentClass: code("./bhrgcom:micaContentClass"),
              micaContentClassArchive: code("./bhrgcom:micaContentClassArchive"),
              organicMatterContentClass: code("./bhrgcom:organicMatterContentClass"),
              organicMatterContentClassNEN5104: code("./bhrgcom:organicMatterContentClassNEN5104"),
              shellMatterContentClass: code("./bhrgcom:shellMatterContentClass"),
              shellMatterContentClassArchive: code("./bhrgcom:shellMatterContentClassArchive"),
              veryCoarseFractionContentClass: array({ each: "./bhrgcom:veryCoarseFractionContentClass", item: code() }),
              veryCoarseFractionContentClassArchive: array({ each: "./bhrgcom:veryCoarseFractionContentClassArchive", item: code() }),
              glauconiteContentClass: code("./bhrgcom:glauconiteContentClass"),
              glauconiteContentClassArchive: code("./bhrgcom:glauconiteContentClassArchive"),
              carbonateContentClass: code("./bhrgcom:carbonateContentClass"),
              colour: code("./bhrgcom:colour"),
              mottled: boolean("./bhrgcom:mottled"),
              fineSoilConsistency: code("./bhrgcom:fineSoilConsistency"),
              organicSoilConsistency: code("./bhrgcom:organicSoilConsistency"),
              sedimentaryPhenomenon: code("./bhrgcom:sedimentaryPhenomenon"),
              organicSoilTexture: code("./bhrgcom:organicSoilTexture"),
              particularConstituent: array({ each: "./bhrgcom:particularConstituent", item: object({ fields: {
                constituentType: code("./bhrgcom:constituentType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
              anomalousLayer: array({ each: "./bhrgcom:anomalousLayer", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                rockType: code("./bhrgcom:rockType"),
                layerProportion: number("./bhrgcom:layerProportion"),
                layerProportionClass: code("./bhrgcom:layerProportionClass"),
                layerProportionClassArchive: code("./bhrgcom:layerProportionClassArchive"),
                stratumThicknessClass: code("./bhrgcom:stratumThicknessClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
                cemented: boolean("./bhrgcom:cemented"),
              } }) }),
              chunk: array({ each: "./bhrgcom:chunk", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                sizeClass: code("./bhrgcom:sizeClass"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
                cemented: boolean("./bhrgcom:cemented"),
              } }) }),
              gravelFraction: object({ at: "./bhrgcom:gravelFraction", fields: {
                gravelMedianClass: code("./bhrgcom:gravelMedianClass"),
                angularity: code("./bhrgcom:angularity"),
                fineGravelContentClass: code("./bhrgcom:fineGravelContentClass"),
                mediumCoarseGravelContentClass: code("./bhrgcom:mediumCoarseGravelContentClass"),
                veryCoarseGravelContentClass: code("./bhrgcom:veryCoarseGravelContentClass"),
                ventifactPresent: text("./bhrgcom:ventifactPresent"),
                sphericity: code("./bhrgcom:sphericity"),
                variegation: code("./bhrgcom:variegation"),
                estimatedMedian: number("./bhrgcom:estimatedMedian"),
                gravelProvenance: code("./bhrgcom:gravelProvenance"),
                gravelConstituent: array({ each: "./bhrgcom:gravelConstituent", item: object({ fields: {
                  gravelType: code("./bhrgcom:gravelType"),
                  fractionProportion: code("./bhrgcom:fractionProportion"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              sandFraction: object({ at: "./bhrgcom:sandFraction", fields: {
                darkGrainContentClass: code("./bhrgcom:darkGrainContentClass"),
                darkGrainContentClassArchive: code("./bhrgcom:darkGrainContentClassArchive"),
                angularity: code("./bhrgcom:angularity"),
                sandMedianClass: code("./bhrgcom:sandMedianClass"),
                sandSorting: code("./bhrgcom:sandSorting"),
                variegation: code("./bhrgcom:variegation"),
                anomalouslyCoarseContentClass: code("./bhrgcom:anomalouslyCoarseContentClass"),
                anomalouslyCoarseContentClassArchive: code("./bhrgcom:anomalouslyCoarseContentClassArchive"),
                granuleContentClass: code("./bhrgcom:granuleContentClass"),
                granuleContentClassArchive: code("./bhrgcom:granuleContentClassArchive"),
                estimatedMedian: number("./bhrgcom:estimatedMedian"),
                sandConstituent: array({ each: "./bhrgcom:sandConstituent", item: object({ fields: {
                  grainColour: code("./bhrgcom:grainColour"),
                  percentageClass: code("./bhrgcom:percentageClass"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              shellFraction: object({ at: "./bhrgcom:shellFraction", fields: {
                gritContentClass: code("./bhrgcom:gritContentClass"),
                fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
                remainsContentClass: code("./bhrgcom:remainsContentClass"),
                wholeContentClass: code("./bhrgcom:wholeContentClass"),
                doublets: boolean("./bhrgcom:doublets"),
                thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
                thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
                inSitu: boolean("./bhrgcom:inSitu"),
                weatheringDegree: code("./bhrgcom:weatheringDegree"),
                shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                  shellTaxon: code("./bhrgcom:shellTaxon"),
                  relativeAbundance: number("./bhrgcom:relativeAbundance"),
                  relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                  relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
                } }) }),
              } }),
              shellFractionArchive: object({ at: "./bhrgcom:shellFractionArchive", fields: {
                gritContentClass: code("./bhrgcom:gritContentClass"),
                fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
                remainsContentClass: code("./bhrgcom:remainsContentClass"),
                wholeContentClass: code("./bhrgcom:wholeContentClass"),
                doublets: boolean("./bhrgcom:doublets"),
                thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
                thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
                weatheringDegree: code("./bhrgcom:weatheringDegree"),
                shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                  shellTaxon: code("./bhrgcom:shellTaxon"),
                  relativeAbundance: number("./bhrgcom:relativeAbundance"),
                  relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                  relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
                } }) }),
              } }),
              peatFraction: object({ at: "./bhrgcom:peatFraction", fields: {
                peatType: code("./bhrgcom:peatType"),
                peatConstituent: array({ each: "./bhrgcom:peatConstituent", item: object({ fields: {
                  plantRemainType: code("./bhrgcom:plantRemainType"),
                  percentageClass: code("./bhrgcom:percentageClass"),
                  archiveClass: code("./bhrgcom:archiveClass"),
                } }) }),
              } }),
              munsellColour: object({ at: "./bhrgcom:munsellColour", fields: {
                munsellHue: code("./bhrgcom:munsellHue"),
                munsellValue: code("./bhrgcom:munsellValue"),
                munsellChroma: code("./bhrgcom:munsellChroma"),
              } }),
              mottle: array({ each: "./bhrgcom:mottle", item: object({ fields: {
                colour: code("./bhrgcom:colour"),
                density: code("./bhrgcom:density"),
                inBands: text("./bhrgcom:inBands"),
              } }) }),
              inclusion: array({ each: "./bhrgcom:inclusion", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              } }) }),
              sedimentLens: array({ each: "./bhrgcom:sedimentLens", item: object({ fields: {
                soilType: code("./bhrgcom:soilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
                colour: code("./bhrgcom:colour"),
                geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              } }) }),
              animalFossil: array({ each: "./bhrgcom:animalFossil", item: object({ fields: {
                animalFossilType: code("./bhrgcom:animalFossilType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
              fractionDistribution: object({ at: "./bhrgcom:fractionDistribution", fields: {
                fractionDistributionComplete: boolean("./bhrgcom:fractionDistributionComplete"),
                estimatedMassProportionOrganicMatter: number("./bhrgcom:estimatedMassProportionOrganicMatter"),
                estimatedMassProportionShellMatter: number("./bhrgcom:estimatedMassProportionShellMatter"),
                estimatedVolumeProportionShellMatter: number("./bhrgcom:estimatedVolumeProportionShellMatter"),
                estimatedMassProportionShell: number("./bhrgcom:estimatedMassProportionShell"),
                estimatedMassProportionGravel: number("./bhrgcom:estimatedMassProportionGravel"),
                estimatedVolumeProportionGravel: number("./bhrgcom:estimatedVolumeProportionGravel"),
                fineFractionDistributionGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionGravellyMineralSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionShellySoil: object({ at: "./bhrgcom:fineFractionDistributionShellySoil", fields: {
                  estimatedVolumeProportionSand: number("./bhrgcom:estimatedVolumeProportionSand"),
                  estimatedVolumeProportionSilt: number("./bhrgcom:estimatedVolumeProportionSilt"),
                  estimatedVolumeProportionLutum: number("./bhrgcom:estimatedVolumeProportionLutum"),
                } }),
                fineFractionDistributionShellySoilArchive: object({ at: "./bhrgcom:fineFractionDistributionShellySoilArchive", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionOrganicSoil: object({ at: "./bhrgcom:fineFractionDistributionOrganicSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
                fineFractionDistributionNonGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionNonGravellyMineralSoil", fields: {
                  estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                  estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                  estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
                } }),
              } }),
            } }),
          } }) }),
          soil: object({ at: "./bhrgcom:soil", fields: {
            geologicalSoilName: code("./bhrgcom:geologicalSoilName"),
            geotechnicalSoilName: code("./bhrgcom:geotechnicalSoilName"),
            soilNameNEN5104: code("./bhrgcom:soilNameNEN5104"),
            gravelContentClass: code("./bhrgcom:gravelContentClass"),
            micaContentClass: code("./bhrgcom:micaContentClass"),
            micaContentClassArchive: code("./bhrgcom:micaContentClassArchive"),
            organicMatterContentClass: code("./bhrgcom:organicMatterContentClass"),
            organicMatterContentClassNEN5104: code("./bhrgcom:organicMatterContentClassNEN5104"),
            shellMatterContentClass: code("./bhrgcom:shellMatterContentClass"),
            shellMatterContentClassArchive: code("./bhrgcom:shellMatterContentClassArchive"),
            veryCoarseFractionContentClass: array({ each: "./bhrgcom:veryCoarseFractionContentClass", item: code() }),
            veryCoarseFractionContentClassArchive: array({ each: "./bhrgcom:veryCoarseFractionContentClassArchive", item: code() }),
            glauconiteContentClass: code("./bhrgcom:glauconiteContentClass"),
            glauconiteContentClassArchive: code("./bhrgcom:glauconiteContentClassArchive"),
            carbonateContentClass: code("./bhrgcom:carbonateContentClass"),
            colour: code("./bhrgcom:colour"),
            mottled: boolean("./bhrgcom:mottled"),
            fineSoilConsistency: code("./bhrgcom:fineSoilConsistency"),
            organicSoilConsistency: code("./bhrgcom:organicSoilConsistency"),
            sedimentaryPhenomenon: code("./bhrgcom:sedimentaryPhenomenon"),
            organicSoilTexture: code("./bhrgcom:organicSoilTexture"),
            particularConstituent: array({ each: "./bhrgcom:particularConstituent", item: object({ fields: {
              constituentType: code("./bhrgcom:constituentType"),
              percentageClass: code("./bhrgcom:percentageClass"),
              archiveClass: code("./bhrgcom:archiveClass"),
            } }) }),
            anomalousLayer: array({ each: "./bhrgcom:anomalousLayer", item: object({ fields: {
              soilType: code("./bhrgcom:soilType"),
              rockType: code("./bhrgcom:rockType"),
              layerProportion: number("./bhrgcom:layerProportion"),
              layerProportionClass: code("./bhrgcom:layerProportionClass"),
              layerProportionClassArchive: code("./bhrgcom:layerProportionClassArchive"),
              stratumThicknessClass: code("./bhrgcom:stratumThicknessClass"),
              colour: code("./bhrgcom:colour"),
              geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              cemented: boolean("./bhrgcom:cemented"),
            } }) }),
            chunk: array({ each: "./bhrgcom:chunk", item: object({ fields: {
              soilType: code("./bhrgcom:soilType"),
              sizeClass: code("./bhrgcom:sizeClass"),
              percentageClass: code("./bhrgcom:percentageClass"),
              archiveClass: code("./bhrgcom:archiveClass"),
              colour: code("./bhrgcom:colour"),
              geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
              cemented: boolean("./bhrgcom:cemented"),
            } }) }),
            gravelFraction: object({ at: "./bhrgcom:gravelFraction", fields: {
              gravelMedianClass: code("./bhrgcom:gravelMedianClass"),
              angularity: code("./bhrgcom:angularity"),
              fineGravelContentClass: code("./bhrgcom:fineGravelContentClass"),
              mediumCoarseGravelContentClass: code("./bhrgcom:mediumCoarseGravelContentClass"),
              veryCoarseGravelContentClass: code("./bhrgcom:veryCoarseGravelContentClass"),
              ventifactPresent: text("./bhrgcom:ventifactPresent"),
              sphericity: code("./bhrgcom:sphericity"),
              variegation: code("./bhrgcom:variegation"),
              estimatedMedian: number("./bhrgcom:estimatedMedian"),
              gravelProvenance: code("./bhrgcom:gravelProvenance"),
              gravelConstituent: array({ each: "./bhrgcom:gravelConstituent", item: object({ fields: {
                gravelType: code("./bhrgcom:gravelType"),
                fractionProportion: code("./bhrgcom:fractionProportion"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
            } }),
            sandFraction: object({ at: "./bhrgcom:sandFraction", fields: {
              darkGrainContentClass: code("./bhrgcom:darkGrainContentClass"),
              darkGrainContentClassArchive: code("./bhrgcom:darkGrainContentClassArchive"),
              angularity: code("./bhrgcom:angularity"),
              sandMedianClass: code("./bhrgcom:sandMedianClass"),
              sandSorting: code("./bhrgcom:sandSorting"),
              variegation: code("./bhrgcom:variegation"),
              anomalouslyCoarseContentClass: code("./bhrgcom:anomalouslyCoarseContentClass"),
              anomalouslyCoarseContentClassArchive: code("./bhrgcom:anomalouslyCoarseContentClassArchive"),
              granuleContentClass: code("./bhrgcom:granuleContentClass"),
              granuleContentClassArchive: code("./bhrgcom:granuleContentClassArchive"),
              estimatedMedian: number("./bhrgcom:estimatedMedian"),
              sandConstituent: array({ each: "./bhrgcom:sandConstituent", item: object({ fields: {
                grainColour: code("./bhrgcom:grainColour"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
            } }),
            shellFraction: object({ at: "./bhrgcom:shellFraction", fields: {
              gritContentClass: code("./bhrgcom:gritContentClass"),
              fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
              remainsContentClass: code("./bhrgcom:remainsContentClass"),
              wholeContentClass: code("./bhrgcom:wholeContentClass"),
              doublets: boolean("./bhrgcom:doublets"),
              thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
              thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
              inSitu: boolean("./bhrgcom:inSitu"),
              weatheringDegree: code("./bhrgcom:weatheringDegree"),
              shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                shellTaxon: code("./bhrgcom:shellTaxon"),
                relativeAbundance: number("./bhrgcom:relativeAbundance"),
                relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
              } }) }),
            } }),
            shellFractionArchive: object({ at: "./bhrgcom:shellFractionArchive", fields: {
              gritContentClass: code("./bhrgcom:gritContentClass"),
              fragmentContentClass: code("./bhrgcom:fragmentContentClass"),
              remainsContentClass: code("./bhrgcom:remainsContentClass"),
              wholeContentClass: code("./bhrgcom:wholeContentClass"),
              doublets: boolean("./bhrgcom:doublets"),
              thickWalledContentClass: code("./bhrgcom:thickWalledContentClass"),
              thinWalledContentClass: code("./bhrgcom:thinWalledContentClass"),
              weatheringDegree: code("./bhrgcom:weatheringDegree"),
              shellConstituent: array({ each: "./bhrgcom:shellConstituent", item: object({ fields: {
                shellTaxon: code("./bhrgcom:shellTaxon"),
                relativeAbundance: number("./bhrgcom:relativeAbundance"),
                relativeAbundanceClass: code("./bhrgcom:relativeAbundanceClass"),
                relativeAbundanceClassArchive: code("./bhrgcom:relativeAbundanceClassArchive"),
              } }) }),
            } }),
            peatFraction: object({ at: "./bhrgcom:peatFraction", fields: {
              peatType: code("./bhrgcom:peatType"),
              peatConstituent: array({ each: "./bhrgcom:peatConstituent", item: object({ fields: {
                plantRemainType: code("./bhrgcom:plantRemainType"),
                percentageClass: code("./bhrgcom:percentageClass"),
                archiveClass: code("./bhrgcom:archiveClass"),
              } }) }),
            } }),
            munsellColour: object({ at: "./bhrgcom:munsellColour", fields: {
              munsellHue: code("./bhrgcom:munsellHue"),
              munsellValue: code("./bhrgcom:munsellValue"),
              munsellChroma: code("./bhrgcom:munsellChroma"),
            } }),
            mottle: array({ each: "./bhrgcom:mottle", item: object({ fields: {
              colour: code("./bhrgcom:colour"),
              density: code("./bhrgcom:density"),
              inBands: text("./bhrgcom:inBands"),
            } }) }),
            inclusion: array({ each: "./bhrgcom:inclusion", item: object({ fields: {
              soilType: code("./bhrgcom:soilType"),
              percentageClass: code("./bhrgcom:percentageClass"),
              archiveClass: code("./bhrgcom:archiveClass"),
              colour: code("./bhrgcom:colour"),
              geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
            } }) }),
            sedimentLens: array({ each: "./bhrgcom:sedimentLens", item: object({ fields: {
              soilType: code("./bhrgcom:soilType"),
              percentageClass: code("./bhrgcom:percentageClass"),
              archiveClass: code("./bhrgcom:archiveClass"),
              colour: code("./bhrgcom:colour"),
              geologicalOrigin: code("./bhrgcom:geologicalOrigin"),
            } }) }),
            animalFossil: array({ each: "./bhrgcom:animalFossil", item: object({ fields: {
              animalFossilType: code("./bhrgcom:animalFossilType"),
              percentageClass: code("./bhrgcom:percentageClass"),
              archiveClass: code("./bhrgcom:archiveClass"),
            } }) }),
            fractionDistribution: object({ at: "./bhrgcom:fractionDistribution", fields: {
              fractionDistributionComplete: boolean("./bhrgcom:fractionDistributionComplete"),
              estimatedMassProportionOrganicMatter: number("./bhrgcom:estimatedMassProportionOrganicMatter"),
              estimatedMassProportionShellMatter: number("./bhrgcom:estimatedMassProportionShellMatter"),
              estimatedVolumeProportionShellMatter: number("./bhrgcom:estimatedVolumeProportionShellMatter"),
              estimatedMassProportionShell: number("./bhrgcom:estimatedMassProportionShell"),
              estimatedMassProportionGravel: number("./bhrgcom:estimatedMassProportionGravel"),
              estimatedVolumeProportionGravel: number("./bhrgcom:estimatedVolumeProportionGravel"),
              fineFractionDistributionGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionGravellyMineralSoil", fields: {
                estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
              } }),
              fineFractionDistributionShellySoil: object({ at: "./bhrgcom:fineFractionDistributionShellySoil", fields: {
                estimatedVolumeProportionSand: number("./bhrgcom:estimatedVolumeProportionSand"),
                estimatedVolumeProportionSilt: number("./bhrgcom:estimatedVolumeProportionSilt"),
                estimatedVolumeProportionLutum: number("./bhrgcom:estimatedVolumeProportionLutum"),
              } }),
              fineFractionDistributionShellySoilArchive: object({ at: "./bhrgcom:fineFractionDistributionShellySoilArchive", fields: {
                estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
              } }),
              fineFractionDistributionOrganicSoil: object({ at: "./bhrgcom:fineFractionDistributionOrganicSoil", fields: {
                estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
              } }),
              fineFractionDistributionNonGravellyMineralSoil: object({ at: "./bhrgcom:fineFractionDistributionNonGravellyMineralSoil", fields: {
                estimatedMassProportionSand: number("./bhrgcom:estimatedMassProportionSand"),
                estimatedMassProportionSilt: number("./bhrgcom:estimatedMassProportionSilt"),
                estimatedMassProportionLutum: number("./bhrgcom:estimatedMassProportionLutum"),
              } }),
            } }),
          } }),
        } }) }),
        notDescribedInterval: array({ each: "./bhrgcom:notDescribedInterval/bhrgcom:NotDescribedInterval", item: object({ fields: {
          beginDepth: number("./bhrgcom:beginDepth"),
          endDepth: number("./bhrgcom:endDepth"),
          noDescriptionReason: code("./bhrgcom:noDescriptionReason"),
        } }) }),
        postSedimentaryDiscontinuity: array({ each: "./bhrgcom:postSedimentaryDiscontinuity/bhrgcom:PostSedimentaryDiscontinuity", item: object({ fields: {
          beginDepth: number("./bhrgcom:beginDepth"),
          endDepth: number("./bhrgcom:endDepth"),
          discontinuityType: code("./bhrgcom:discontinuityType"),
        } }) }),
      } }) }),
    } }),
    boreholeSampleAnalysis: object({ at: "./dsbhrg:boreholeSampleAnalysis/bhrgcom:BoreholeSampleAnalysis", fields: {
      analysisReportDate: date("./bhrgcom:analysisReportDate"),
      analysisProcedure: code("./bhrgcom:analysisProcedure"),
      analysisOperator: object({ at: "./bhrgcom:analysisOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
      investigatedInterval: array({ each: "./bhrgcom:investigatedInterval/bhrgcom:InvestigatedInterval", item: object({ fields: {
        beginDepth: number("./bhrgcom:beginDepth"),
        endDepth: number("./bhrgcom:endDepth"),
        sampleQuality: code("./bhrgcom:sampleQuality"),
        determinedCompositionProperties: code("./bhrgcom:determinedCompositionProperties"),
        determinedHydrophysicalProperties: code("./bhrgcom:determinedHydrophysicalProperties"),
        waterContentDetermined: boolean("./bhrgcom:waterContentDetermined"),
        volumetricMassDensityDetermined: boolean("./bhrgcom:volumetricMassDensityDetermined"),
        described: boolean("./bhrgcom:described"),
        investigatedMaterial: object({ at: "./bhrgcom:investigatedMaterial", fields: {
          specialMaterial: code("./bhrgcom:specialMaterial"),
          geologicalSoilName: code("./bhrgcom:geologicalSoilName"),
          geotechnicalSoilName: code("./bhrgcom:geotechnicalSoilName"),
          gravelContentClass: code("./bhrgcom:gravelContentClass"),
          organicMatterContentClass: code("./bhrgcom:organicMatterContentClass"),
          organicMatterContentClassNEN5104: code("./bhrgcom:organicMatterContentClassNEN5104"),
          shellMatterContentClass: code("./bhrgcom:shellMatterContentClass"),
          carbonateContentClass: code("./bhrgcom:carbonateContentClass"),
          particularConstituent: array({ each: "./bhrgcom:particularConstituent", item: code() }),
          sandMedianClass: code("./bhrgcom:sandMedianClass"),
          shellGritContentClass: code("./bhrgcom:shellGritContentClass"),
          shellFragmentContentClass: code("./bhrgcom:shellFragmentContentClass"),
          wholeShellContentClass: code("./bhrgcom:wholeShellContentClass"),
          anomalousMaterial: array({ each: "./bhrgcom:anomalousMaterial", item: object({ fields: {
            materialShape: code("./bhrgcom:materialShape"),
            soilType: code("./bhrgcom:soilType"),
            rockType: code("./bhrgcom:rockType"),
            percentageClass: code("./bhrgcom:percentageClass"),
          } }) }),
        } }),
        particleSizeDistributionDetermination: array({ each: "./bhrgcom:particleSizeDistributionDetermination/bhrgcom:ParticleSizeDistributionDetermination", item: object({ fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          fractionDistribution: code("./bhrgcom:fractionDistribution"),
          removalMethodOrganicMatter: code("./bhrgcom:removalMethodOrganicMatter"),
          removalMethodCarbonate: code("./bhrgcom:removalMethodCarbonate"),
          removedMaterial: array({ each: "./bhrgcom:removedMaterial", item: code() }),
          massDryMaterial: number("./bhrgcom:massDryMaterial"),
          calculationValueParticleDensity: number("./bhrgcom:calculationValueParticleDensity"),
          dispersionMethod: code("./bhrgcom:dispersionMethod"),
          calculationValueOrigin: code("./bhrgcom:calculationValueOrigin"),
          appliedOpticalModel: code("./bhrgcom:appliedOpticalModel"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          basicParticleSizeDistribution: object({ at: "./bhrgcom:basicParticleSizeDistribution", fields: {
            fractionSmaller63um: number("./bhrgcom:fractionSmaller63um"),
            fraction63umTo2mm: number("./bhrgcom:fraction63umTo2mm"),
            fractionLarger2mm: number("./bhrgcom:fractionLarger2mm"),
            standardDistributionFractionSmaller63um: object({ at: "./bhrgcom:standardDistributionFractionSmaller63um", fields: {
              "fraction0to0.2um": number("./bhrgcom:fraction0to0.2um"),
              "fraction0.2to0.5um": number("./bhrgcom:fraction0.2to0.5um"),
              "fraction0.5to1um": number("./bhrgcom:fraction0.5to1um"),
              fraction1to2um: number("./bhrgcom:fraction1to2um"),
              fraction2to4um: number("./bhrgcom:fraction2to4um"),
              fraction4to8um: number("./bhrgcom:fraction4to8um"),
              fraction8to16um: number("./bhrgcom:fraction8to16um"),
              fraction16to25um: number("./bhrgcom:fraction16to25um"),
              fraction25to32um: number("./bhrgcom:fraction25to32um"),
              fraction32to50um: number("./bhrgcom:fraction32to50um"),
              fraction50to63um: number("./bhrgcom:fraction50to63um"),
            } }),
            minimalDistributionFractionSmaller63um: object({ at: "./bhrgcom:minimalDistributionFractionSmaller63um", fields: {
              fraction0to2um: number("./bhrgcom:fraction0to2um"),
              fraction2to4um: number("./bhrgcom:fraction2to4um"),
              fraction4to8um: number("./bhrgcom:fraction4to8um"),
              fraction8to16um: number("./bhrgcom:fraction8to16um"),
              fraction16to32um: number("./bhrgcom:fraction16to32um"),
              fraction32to50um: number("./bhrgcom:fraction32to50um"),
              fraction50to63um: number("./bhrgcom:fraction50to63um"),
            } }),
            standardDistributionFraction63umTo2mm: object({ at: "./bhrgcom:standardDistributionFraction63umTo2mm", fields: {
              fraction63to75um: number("./bhrgcom:fraction63to75um"),
              fraction75to90um: number("./bhrgcom:fraction75to90um"),
              fraction90to105um: number("./bhrgcom:fraction90to105um"),
              fraction105to125um: number("./bhrgcom:fraction105to125um"),
              fraction125to150um: number("./bhrgcom:fraction125to150um"),
              fraction150to180um: number("./bhrgcom:fraction150to180um"),
              fraction180to200um: number("./bhrgcom:fraction180to200um"),
              fraction200to210um: number("./bhrgcom:fraction200to210um"),
              fraction210to250um: number("./bhrgcom:fraction210to250um"),
              fraction250to300um: number("./bhrgcom:fraction250to300um"),
              fraction300to355um: number("./bhrgcom:fraction300to355um"),
              fraction355to420um: number("./bhrgcom:fraction355to420um"),
              fraction420to500um: number("./bhrgcom:fraction420to500um"),
              fraction500to600um: number("./bhrgcom:fraction500to600um"),
              fraction600to630um: number("./bhrgcom:fraction600to630um"),
              fraction630to710um: number("./bhrgcom:fraction630to710um"),
              fraction710to850um: number("./bhrgcom:fraction710to850um"),
              fraction850to1000um: number("./bhrgcom:fraction850to1000um"),
              fraction1000to1200um: number("./bhrgcom:fraction1000to1200um"),
              fraction1200to1400um: number("./bhrgcom:fraction1200to1400um"),
              fraction1400to1700um: number("./bhrgcom:fraction1400to1700um"),
              fraction1700umTo2mm: number("./bhrgcom:fraction1700umTo2mm"),
            } }),
            minimalDistributionFraction63umTo2mm: object({ at: "./bhrgcom:minimalDistributionFraction63umTo2mm", fields: {
              fraction63to90um: number("./bhrgcom:fraction63to90um"),
              fraction90to105um: number("./bhrgcom:fraction90to105um"),
              fraction105to125um: number("./bhrgcom:fraction105to125um"),
              fraction125to150um: number("./bhrgcom:fraction125to150um"),
              fraction150to180um: number("./bhrgcom:fraction150to180um"),
              fraction180to200um: number("./bhrgcom:fraction180to200um"),
              fraction200to210um: number("./bhrgcom:fraction200to210um"),
              fraction210to250um: number("./bhrgcom:fraction210to250um"),
              fraction250to300um: number("./bhrgcom:fraction250to300um"),
              fraction300to355um: number("./bhrgcom:fraction300to355um"),
              fraction355to420um: number("./bhrgcom:fraction355to420um"),
              fraction420to500um: number("./bhrgcom:fraction420to500um"),
              fraction500to600um: number("./bhrgcom:fraction500to600um"),
              fraction600to630um: number("./bhrgcom:fraction600to630um"),
              fraction630to710um: number("./bhrgcom:fraction630to710um"),
              fraction710to1000um: number("./bhrgcom:fraction710to1000um"),
              fraction1000to1400um: number("./bhrgcom:fraction1000to1400um"),
              fraction1400umTo2mm: number("./bhrgcom:fraction1400umTo2mm"),
            } }),
            limitedDistributionFraction63umTo2mm: object({ at: "./bhrgcom:limitedDistributionFraction63umTo2mm", fields: {
              fraction63to300um: number("./bhrgcom:fraction63to300um"),
              fraction300to420um: number("./bhrgcom:fraction300to420um"),
              fraction420to600um: number("./bhrgcom:fraction420to600um"),
              fraction600to630um: number("./bhrgcom:fraction600to630um"),
              fraction630to1000um: number("./bhrgcom:fraction630to1000um"),
              fraction1000to1200um: number("./bhrgcom:fraction1000to1200um"),
              fraction1200to1400um: number("./bhrgcom:fraction1200to1400um"),
              fraction1400umTo2mm: number("./bhrgcom:fraction1400umTo2mm"),
            } }),
            standardDistributionFractionLarger2mm: object({ at: "./bhrgcom:standardDistributionFractionLarger2mm", fields: {
              "fraction2to5.6mm": number("./bhrgcom:fraction2to5.6mm"),
              "fraction5.6to6.3mm": number("./bhrgcom:fraction5.6to6.3mm"),
              "fraction6.3to10mm": number("./bhrgcom:fraction6.3to10mm"),
              fraction10to16mm: number("./bhrgcom:fraction10to16mm"),
              fraction16to20mm: number("./bhrgcom:fraction16to20mm"),
              "fraction20to37.5mm": number("./bhrgcom:fraction20to37.5mm"),
              "fraction37.5to63mm": number("./bhrgcom:fraction37.5to63mm"),
              fractionLarger63mm: number("./bhrgcom:fractionLarger63mm"),
            } }),
          } }),
        } }) }),
        carbonateContentDetermination: object({ at: "./bhrgcom:carbonateContentDetermination/bhrgcom:CarbonateContentDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          dryingPeriod: code("./bhrgcom:dryingPeriod"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          carbonateContent: number("./bhrgcom:carbonateContent"),
          massLossCarbonateContent: object({ at: "./bhrgcom:massLossCarbonateContent", fields: {
            mass105DegreesCelsius: number("./bhrgcom:mass105DegreesCelsius"),
            mass800DegreesCelsius: number("./bhrgcom:mass800DegreesCelsius"),
            mass1000DegreesCelsius: number("./bhrgcom:mass1000DegreesCelsius"),
          } }),
        } }),
        organicMatterContentDetermination: object({ at: "./bhrgcom:organicMatterContentDetermination/bhrgcom:OrganicMatterContentDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          dryingPeriod: code("./bhrgcom:dryingPeriod"),
          lutumCorrectionApplied: boolean("./bhrgcom:lutumCorrectionApplied"),
          freeIronCorrectionApplied: boolean("./bhrgcom:freeIronCorrectionApplied"),
          freeIronContent: number("./bhrgcom:freeIronContent"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          organicMatterContent: number("./bhrgcom:organicMatterContent"),
          massLossOrganicMatterContent: object({ at: "./bhrgcom:massLossOrganicMatterContent", fields: {
            mass105DegreesCelsius: number("./bhrgcom:mass105DegreesCelsius"),
            mass450DegreesCelsius: number("./bhrgcom:mass450DegreesCelsius"),
            mass550DegreesCelsius: number("./bhrgcom:mass550DegreesCelsius"),
          } }),
        } }),
        organicCarbonContentDetermination: object({ at: "./bhrgcom:organicCarbonContentDetermination/bhrgcom:OrganicCarbonContentDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          detectionLimit: number("./bhrgcom:detectionLimit"),
          organicCarbonContent: number("./bhrgcom:organicCarbonContent"),
        } }),
        sulfurContentDetermination: object({ at: "./bhrgcom:sulfurContentDetermination/bhrgcom:SulfurContentDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          detectionLimit: number("./bhrgcom:detectionLimit"),
          sulfurContent: number("./bhrgcom:sulfurContent"),
        } }),
        saturatedPermeabilityDetermination: object({ at: "./bhrgcom:saturatedPermeabilityDetermination/bhrgcom:SaturatedPermeabilityDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          verticallyDetermined: boolean("./bhrgcom:verticallyDetermined"),
          saturationMethod: code("./bhrgcom:saturationMethod"),
          usedMedium: code("./bhrgcom:usedMedium"),
          waterDegassed: boolean("./bhrgcom:waterDegassed"),
          volumetricMassDensityWater: number("./bhrgcom:volumetricMassDensityWater"),
          porousDiscWet: boolean("./bhrgcom:porousDiscWet"),
          verticalStrain: number("./bhrgcom:verticalStrain"),
          swellObserved: boolean("./bhrgcom:swellObserved"),
          ringWaterRepellent: boolean("./bhrgcom:ringWaterRepellent"),
          currentDownwards: boolean("./bhrgcom:currentDownwards"),
          temperature: number("./bhrgcom:temperature"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          maximumGradient: number("./bhrgcom:maximumGradient"),
          waterContentAfterwards: number("./bhrgcom:waterContentAfterwards"),
          saturatedPermeabilityAtSpecificLoad: object({ at: "./bhrgcom:saturatedPermeabilityAtSpecificLoad", fields: {
            load: number("./bhrgcom:load"),
            saturatedPermeability: number("./bhrgcom:saturatedPermeability"),
          } }),
        } }),
        waterContentDetermination: object({ at: "./bhrgcom:waterContentDetermination/bhrgcom:WaterContentDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          sampleMoistness: code("./bhrgcom:sampleMoistness"),
          removedMaterial: array({ each: "./bhrgcom:removedMaterial", item: code() }),
          dryingTemperature: code("./bhrgcom:dryingTemperature"),
          dryingPeriod: code("./bhrgcom:dryingPeriod"),
          saltCorrectionMethod: code("./bhrgcom:saltCorrectionMethod"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          waterContent: number("./bhrgcom:waterContent"),
        } }),
        volumetricMassDensityDetermination: object({ at: "./bhrgcom:volumetricMassDensityDetermination/bhrgcom:VolumetricMassDensityDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          sampleMoistness: code("./bhrgcom:sampleMoistness"),
          specimenVolume: number("./bhrgcom:specimenVolume"),
          underLoad: boolean("./bhrgcom:underLoad"),
          verticalStrain: number("./bhrgcom:verticalStrain"),
          saturated: boolean("./bhrgcom:saturated"),
          swellObserved: boolean("./bhrgcom:swellObserved"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          volumetricMassDensity: number("./bhrgcom:volumetricMassDensity"),
        } }),
        volumetricMassDryDensityDetermination: object({ at: "./bhrgcom:volumetricMassDryDensityDetermination/bhrgcom:VolumetricMassDryDensityDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          sampleMoistness: code("./bhrgcom:sampleMoistness"),
          specimenVolume: number("./bhrgcom:specimenVolume"),
          underLoad: boolean("./bhrgcom:underLoad"),
          verticalStrain: number("./bhrgcom:verticalStrain"),
          saturated: boolean("./bhrgcom:saturated"),
          swellObserved: boolean("./bhrgcom:swellObserved"),
          dryingTemperature: code("./bhrgcom:dryingTemperature"),
          dryingPeriod: code("./bhrgcom:dryingPeriod"),
          saltCorrectionMethod: code("./bhrgcom:saltCorrectionMethod"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          volumetricMassDryDensity: number("./bhrgcom:volumetricMassDryDensity"),
        } }),
        volumetricMassDensitySolidsDetermination: object({ at: "./bhrgcom:volumetricMassDensitySolidsDetermination/bhrgcom:VolumetricMassDensitySolidsDetermination", fields: {
          determinationProcedure: code("./bhrgcom:determinationProcedure"),
          determinationMethod: code("./bhrgcom:determinationMethod"),
          removedMaterial: array({ each: "./bhrgcom:removedMaterial", item: code() }),
          usedMedium: code("./bhrgcom:usedMedium"),
          sampleContainerVolume: code("./bhrgcom:sampleContainerVolume"),
          performanceIrregularity: array({ each: "./bhrgcom:performanceIrregularity", item: code() }),
          materialIrregularity: array({ each: "./bhrgcom:materialIrregularity", item: code() }),
          volumetricMassDensitySolids: number("./bhrgcom:volumetricMassDensitySolids"),
        } }),
      } }) }),
    } }),
  },
});
