/**
 * BHR-GT schema — GENERATED from the official XSD by scripts/codegen-schema.ts.
 * Do not edit by hand. Structural warts are supplied by ./bore-curation.ts.
 *
 * @generated from https://schema.broservices.nl/xsd/dsbhr-gt/2.1/dsbhr-gt-messages.xsd
 */

import { array, boolean, code, date, number, object, text } from "../core/producer.js";
import { gmlLocation } from "./common-fields.js";
import { ANALYSIS_PRODUCER } from "./bhrgt-analysis.js";

export const BORE_PRODUCER = object({
  fields: {
    broId: text("./brocom:broId"),
    deliveryAccountableParty: text("./brocom:deliveryAccountableParty"),
    objectIdAccountableParty: text("./brocom:objectIdAccountableParty"),
    deliveryResponsibleParty: text("./brocom:deliveryResponsibleParty"),
    qualityRegime: text("./brocom:qualityRegime"),
    deliveryContext: code("./dsbhrgt:deliveryContext"),
    surveyPurpose: code("./dsbhrgt:surveyPurpose"),
    discipline: code("./dsbhrgt:discipline"),
    surveyProcedure: code("./dsbhrgt:surveyProcedure"),
    researchReportDate: date("./dsbhrgt:researchReportDate"),
    researchOperator: object({ at: "./dsbhrgt:researchOperator", fields: {
      chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
      europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
    } }),
    siteCharacteristicDetermined: boolean("./dsbhrgt:siteCharacteristicDetermined"),
    registrationHistory: object({ at: "./dsbhrgt:registrationHistory", fields: {
      objectRegistrationTime: date("./brocom:objectRegistrationTime"),
      registrationStatus: code("./brocom:registrationStatus"),
      latestAdditionTime: date("./brocom:latestAdditionTime"),
      registrationCompletionTime: date("./brocom:registrationCompletionTime"),
      corrected: boolean("./brocom:corrected"),
      latestCorrectionTime: date("./brocom:latestCorrectionTime"),
      underReview: boolean("./brocom:underReview"),
      underReviewTime: date("./brocom:underReviewTime"),
      deregistered: boolean("./brocom:deregistered"),
      deregistrationTime: date("./brocom:deregistrationTime"),
      reregistered: boolean("./brocom:reregistered"),
      reregistrationTime: date("./brocom:reregistrationTime"),
    } }),
    reportHistory: object({ at: "./dsbhrgt:reportHistory", fields: {
      reportStartDate: date("./dsbhrgt:reportStartDate"),
      reportEndDate: date("./dsbhrgt:reportEndDate"),
      intermediateEvent: array({ each: "./dsbhrgt:intermediateEvent", item: object({ fields: {
        eventName: code("./dsbhrgt:eventName"),
        eventDate: date("./dsbhrgt:eventDate"),
      } }) }),
    } }),
    deliveredLocation: object({ at: "./dsbhrgt:deliveredLocation", fields: {
      location: gmlLocation("./bhrgtcom:location"),
      horizontalPositioningDate: date("./bhrgtcom:horizontalPositioningDate"),
      horizontalPositioningMethod: code("./bhrgtcom:horizontalPositioningMethod"),
      horizontalPositioningOperator: object({ at: "./bhrgtcom:horizontalPositioningOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
    } }),
    deliveredVerticalPosition: object({ at: "./dsbhrgt:deliveredVerticalPosition", fields: {
      localVerticalReferencePoint: code("./bhrgtcom:localVerticalReferencePoint"),
      offset: number("./bhrgtcom:offset"),
      waterDepth: number("./bhrgtcom:waterDepth"),
      verticalDatum: code("./bhrgtcom:verticalDatum"),
      verticalPositioningDate: date("./bhrgtcom:verticalPositioningDate"),
      verticalPositioningMethod: code("./bhrgtcom:verticalPositioningMethod"),
      verticalPositioningOperator: object({ at: "./bhrgtcom:verticalPositioningOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
    } }),
    standardizedLocation: object({ at: "./dsbhrgt:standardizedLocation", fields: {
      location: gmlLocation("./brocom:location"),
      coordinateTransformation: code("./brocom:coordinateTransformation"),
    } }),
    boring: object({ at: "./dsbhrgt:boring", fields: {
      boringStartDate: date("./bhrgtcom:boringStartDate"),
      boringEndDate: date("./bhrgtcom:boringEndDate"),
      boringOperator: object({ at: "./bhrgtcom:boringOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
      preparation: code("./bhrgtcom:preparation"),
      finalDepthPreparation: number("./bhrgtcom:finalDepthPreparation"),
      trajectoryExcavated: boolean("./bhrgtcom:trajectoryExcavated"),
      finalDepthExcavation: number("./bhrgtcom:finalDepthExcavation"),
      rockReached: boolean("./bhrgtcom:rockReached"),
      boringProcedure: array({ each: "./bhrgtcom:boringProcedure", item: code() }),
      finalDepthBoring: number("./bhrgtcom:finalDepthBoring"),
      stopCriterion: code("./bhrgtcom:stopCriterion"),
      temporaryCasingUsed: boolean("./bhrgtcom:temporaryCasingUsed"),
      finalDepthTemporaryCasing: number("./bhrgtcom:finalDepthTemporaryCasing"),
      flushingMediumUsed: text("./bhrgtcom:flushingMediumUsed"),
      flushingAdditive: code("./bhrgtcom:flushingAdditive"),
      groundwaterLevel: number("./bhrgtcom:groundwaterLevel"),
      samplingProcedure: code("./bhrgtcom:samplingProcedure"),
      finalDepthSampling: number("./bhrgtcom:finalDepthSampling"),
      subsurfaceContaminated: boolean("./bhrgtcom:subsurfaceContaminated"),
      boreholeCompleted: text("./bhrgtcom:boreholeCompleted"),
      excavatedLayer: array({ each: "./bhrgtcom:excavatedLayer", item: object({ fields: {
        upperBoundary: number("./bhrgtcom:upperBoundary"),
        lowerBoundary: number("./bhrgtcom:lowerBoundary"),
        excavatedMaterial: code("./bhrgtcom:excavatedMaterial"),
      } }) }),
      boredInterval: array({ each: "./bhrgtcom:boredInterval", item: object({ fields: {
        beginDepth: number("./bhrgtcom:beginDepth"),
        endDepth: number("./bhrgtcom:endDepth"),
        boringTechnique: code("./bhrgtcom:boringTechnique"),
        boredDiameter: number("./bhrgtcom:boredDiameter"),
      } }) }),
      boringVelocity: array({ each: "./bhrgtcom:boringVelocity", item: object({ fields: {
        elapsedTime: number("./bhrgtcom:elapsedTime"),
        depth: number("./bhrgtcom:depth"),
      } }) }),
      sampledInterval: array({ each: "./bhrgtcom:sampledInterval", item: object({ fields: {
        beginDepth: number("./bhrgtcom:beginDepth"),
        endDepth: number("./bhrgtcom:endDepth"),
        preTreatment: code("./bhrgtcom:preTreatment"),
        samplingMethod: code("./bhrgtcom:samplingMethod"),
        samplingQuality: code("./bhrgtcom:samplingQuality"),
        orientatedSampled: boolean("./bhrgtcom:orientatedSampled"),
        sampler: object({ at: "./bhrgtcom:sampler", fields: {
          samplerType: code("./bhrgtcom:samplerType"),
          sampleContainerDiameter: number("./bhrgtcom:sampleContainerDiameter"),
          sampleContainerLength: number("./bhrgtcom:sampleContainerLength"),
          cuttingShoeInsideDiameter: number("./bhrgtcom:cuttingShoeInsideDiameter"),
          stockingUsed: boolean("./bhrgtcom:stockingUsed"),
          rightAngledCuttingShoe: boolean("./bhrgtcom:rightAngledCuttingShoe"),
          taperAngle: number("./bhrgtcom:taperAngle"),
          cuttingShoeOutsideDiameter: number("./bhrgtcom:cuttingShoeOutsideDiameter"),
          lubricationFluidUsed: boolean("./bhrgtcom:lubricationFluidUsed"),
          coreCatcherPresent: boolean("./bhrgtcom:coreCatcherPresent"),
          pistonPresent: boolean("./bhrgtcom:pistonPresent"),
        } }),
        coreRecovery: object({ at: "./bhrgtcom:coreRecovery", fields: {
          totalCoreRecovery: number("./bhrgtcom:totalCoreRecovery"),
          solidCoreRecovery: number("./bhrgtcom:solidCoreRecovery"),
          rockQualityDesignation: number("./bhrgtcom:rockQualityDesignation"),
          fieldDetermined: boolean("./bhrgtcom:fieldDetermined"),
        } }),
      } }) }),
      contaminatedInterval: array({ each: "./bhrgtcom:contaminatedInterval", item: object({ fields: {
        beginDepth: number("./bhrgtcom:beginDepth"),
        endDepth: number("./bhrgtcom:endDepth"),
      } }) }),
      completedInterval: array({ each: "./bhrgtcom:completedInterval", item: object({ fields: {
        beginDepth: number("./bhrgtcom:beginDepth"),
        endDepth: number("./bhrgtcom:endDepth"),
        permanentCasingPresent: boolean("./bhrgtcom:permanentCasingPresent"),
        diameterPermanentCasing: number("./bhrgtcom:diameterPermanentCasing"),
        materialPermanentCasing: code("./bhrgtcom:materialPermanentCasing"),
        backfillMaterial: code("./bhrgtcom:backfillMaterial"),
        backfillMaterialWashed: boolean("./bhrgtcom:backfillMaterialWashed"),
        backfillMaterialCertified: boolean("./bhrgtcom:backfillMaterialCertified"),
      } }) }),
    } }),
    siteCharacteristic: object({ at: "./dsbhrgt:siteCharacteristic", fields: {
      soilUse: code("./bhrgtcom:soilUse"),
      positionOnGroundBody: code("./bhrgtcom:positionOnGroundBody"),
      temporaryChange: code("./bhrgtcom:temporaryChange"),
    } }),
    fluidMudLayer: object({ at: "./dsbhrgt:fluidMudLayer", fields: {
      thickness: number("./bhrgtcom:thickness"),
      colour: code("./bhrgtcom:colour"),
      upperBoundaryPositioningMethod: code("./bhrgtcom:upperBoundaryPositioningMethod"),
      lowerBoundaryPositioningMethod: code("./bhrgtcom:lowerBoundaryPositioningMethod"),
    } }),
    boreholeSampleDescription: object({ at: "./dsbhrgt:boreholeSampleDescription", fields: {
      descriptionReportDate: date("./bhrgtcom:descriptionReportDate"),
      descriptionProcedure: array({ each: "./bhrgtcom:descriptionProcedure", item: code() }),
      descriptionOperator: object({ at: "./bhrgtcom:descriptionOperator", fields: {
        chamberOfCommerceNumber: text("./brocom:chamberOfCommerceNumber"),
        europeanCompanyRegistrationNumber: text("./brocom:europeanCompanyRegistrationNumber"),
      } }),
      descriptiveBoreholeLog: array({ each: "./bhrgtcom:descriptiveBoreholeLog", item: object({ fields: {
        descriptionQuality: code("./bhrgtcom:descriptionQuality"),
        continuouslySampled: text("./bhrgtcom:continuouslySampled"),
        descriptionLocation: code("./bhrgtcom:descriptionLocation"),
        describedMaterial: code("./bhrgtcom:describedMaterial"),
        sampleMoistness: code("./bhrgtcom:sampleMoistness"),
        boreholeLogChecked: boolean("./bhrgtcom:boreholeLogChecked"),
        meanHighestGroundwaterLevel: number("./bhrgtcom:meanHighestGroundwaterLevel"),
        meanLowestGroundwaterLevel: number("./bhrgtcom:meanLowestGroundwaterLevel"),
        layer: array({ each: "./bhrgtcom:layer", item: object({ fields: {
          upperBoundary: number("./bhrgtcom:upperBoundary"),
          upperBoundaryDetermination: code("./bhrgtcom:upperBoundaryDetermination"),
          lowerBoundary: number("./bhrgtcom:lowerBoundary"),
          lowerBoundaryDetermination: code("./bhrgtcom:lowerBoundaryDetermination"),
          anthropogenic: text("./bhrgtcom:anthropogenic"),
          activityType: code("./bhrgtcom:activityType"),
          specialMaterial: code("./bhrgtcom:specialMaterial"),
          slant: boolean("./bhrgtcom:slant"),
          internalStructureIntact: boolean("./bhrgtcom:internalStructureIntact"),
          bedded: boolean("./bhrgtcom:bedded"),
          compositeLayer: boolean("./bhrgtcom:compositeLayer"),
          bedding: code("./bhrgtcom:bedding"),
          soil: object({ at: "./bhrgtcom:soil", fields: {
            geotechnicalSoilName: code("./bhrgtcom:geotechnicalSoilName"),
            soilNameNEN5104: code("./bhrgtcom:soilNameNEN5104"),
            gravelContentClassNEN5104: code("./bhrgtcom:gravelContentClassNEN5104"),
            organicMatterContentClassNEN5104: code("./bhrgtcom:organicMatterContentClassNEN5104"),
            tertiaryConstituent: array({ each: "./bhrgtcom:tertiaryConstituent", item: code() }),
            colour: code("./bhrgtcom:colour"),
            mottled: boolean("./bhrgtcom:mottled"),
            interbedding: code("./bhrgtcom:interbedding"),
            dispersedInhomogeneity: array({ each: "./bhrgtcom:dispersedInhomogeneity", item: code() }),
            carbonateContentClass: code("./bhrgtcom:carbonateContentClass"),
            organicMatterContentClass: code("./bhrgtcom:organicMatterContentClass"),
            crossBedding: boolean("./bhrgtcom:crossBedding"),
            gradedBedding: boolean("./bhrgtcom:gradedBedding"),
            mixed: boolean("./bhrgtcom:mixed"),
            mixingType: code("./bhrgtcom:mixingType"),
            gravelMedianClass: code("./bhrgtcom:gravelMedianClass"),
            fineGravelContentClass: code("./bhrgtcom:fineGravelContentClass"),
            mediumCoarseGravelContentClass: code("./bhrgtcom:mediumCoarseGravelContentClass"),
            veryCoarseGravelContentClass: code("./bhrgtcom:veryCoarseGravelContentClass"),
            sandMedianClass: code("./bhrgtcom:sandMedianClass"),
            sandSortingNEN5104: code("./bhrgtcom:sandSortingNEN5104"),
            peatType: code("./bhrgtcom:peatType"),
            organicSoilTexture: code("./bhrgtcom:organicSoilTexture"),
            fineSoilConsistency: code("./bhrgtcom:fineSoilConsistency"),
            organicSoilConsistency: code("./bhrgtcom:organicSoilConsistency"),
            peatTensileStrength: code("./bhrgtcom:peatTensileStrength"),
            geotechnicalDepositionalCharacteristic: code("./bhrgtcom:geotechnicalDepositionalCharacteristic"),
            depositionalAge: code("./bhrgtcom:depositionalAge"),
            grainshape: object({ at: "./bhrgtcom:grainshape", fields: {
              sizeFraction: code("./bhrgtcom:sizeFraction"),
              angularity: code("./bhrgtcom:angularity"),
              sphericity: code("./bhrgtcom:sphericity"),
              roughness: code("./bhrgtcom:roughness"),
            } }),
          } }),
          rock: object({ at: "./bhrgtcom:rock", fields: {
            rockType: code("./bhrgtcom:rockType"),
            cementType: code("./bhrgtcom:cementType"),
            colour: code("./bhrgtcom:colour"),
            tertiaryRockConstituent: array({ each: "./bhrgtcom:tertiaryRockConstituent", item: code() }),
            interbedding: code("./bhrgtcom:interbedding"),
            dispersedInhomogeneity: array({ each: "./bhrgtcom:dispersedInhomogeneity", item: code() }),
            carbonateContentClass: code("./bhrgtcom:carbonateContentClass"),
            crossBedding: boolean("./bhrgtcom:crossBedding"),
            gradedBedding: boolean("./bhrgtcom:gradedBedding"),
            voidsPresent: boolean("./bhrgtcom:voidsPresent"),
            voidDistribution: code("./bhrgtcom:voidDistribution"),
            stability: code("./bhrgtcom:stability"),
            strengthClass: code("./bhrgtcom:strengthClass"),
            weathered: boolean("./bhrgtcom:weathered"),
            weatheringDegree: object({ at: "./bhrgtcom:weatheringDegree", fields: {
              discolouration: code("./bhrgtcom:discolouration"),
              disintegration: code("./bhrgtcom:disintegration"),
              decomposition: code("./bhrgtcom:decomposition"),
            } }),
          } }),
        } }) }),
        notDescribedInterval: array({ each: "./bhrgtcom:notDescribedInterval", item: object({ fields: {
          beginDepth: number("./bhrgtcom:beginDepth"),
          endDepth: number("./bhrgtcom:endDepth"),
          noDescriptionReason: code("./bhrgtcom:noDescriptionReason"),
        } }) }),
        postSedimentaryDiscontinuity: array({ each: "./bhrgtcom:postSedimentaryDiscontinuity", item: object({ fields: {
          beginDepth: number("./bhrgtcom:beginDepth"),
          endDepth: number("./bhrgtcom:endDepth"),
          inRock: boolean("./bhrgtcom:inRock"),
          discontinuityType: code("./bhrgtcom:discontinuityType"),
          compositeDiscontinuity: boolean("./bhrgtcom:compositeDiscontinuity"),
          spacing: number("./bhrgtcom:spacing"),
          smooth: boolean("./bhrgtcom:smooth"),
          apertureClass: code("./bhrgtcom:apertureClass"),
          infillMaterial: code("./bhrgtcom:infillMaterial"),
        } }) }),
      } }) }),
    } }),
    analysis: ANALYSIS_PRODUCER,
  },
});
